#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: sơn giả đá

# Short bio or description (displayed in the header)
description: Sơn giả đá Nguyễn Cường là đơn vị chuyên cung cấp, tư vấn, thi công sơn giả đá và lập dự toán sơn tại Việt Nam. Không ngừng cải thiện nâng cao giá trị sản phẩm.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://songiada.co/wp-content/uploads/2017/04/decor-paint-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:https://www.flickr.com/people/songiada/
  github: https://songiada.github.io/
  instagram:
  linkedin:https://www.linkedin.com/in/songiada/
  pinterest:https://www.pinterest.com/songiadaco2019/
  rss: # just type anything here for a working RSS icon
  twitter: https://twitter.com/Songiada3
  


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/songiada"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
